// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddGitRemote(arg1:string,arg2:string):Promise<void>;

export function CreateNewFile(arg1:string):Promise<void>;

export function CreateNewFolder(arg1:string):Promise<void>;

export function DeleteItem(arg1:string):Promise<void>;

export function GetAppVersion():Promise<string>;

export function GetFolderContents(arg1:string):Promise<Array<main.FileItem>>;

export function GetGitStatus(arg1:string):Promise<Record<string, string>>;

export function GitCommitAndPush(arg1:string,arg2:string):Promise<string>;

export function GitInit(arg1:string):Promise<string>;

export function GitPull(arg1:string):Promise<string>;

export function GitReset(arg1:string):Promise<string>;

export function OpenFile():Promise<main.FileInfo>;

export function OpenFolderDialog():Promise<main.FolderInfo>;

export function ReadFileByPath(arg1:string):Promise<string>;

export function RenameItem(arg1:string,arg2:string):Promise<void>;

export function RunCommand(arg1:string,arg2:string):Promise<string>;

export function SaveFile(arg1:string,arg2:string):Promise<string>;

export function SearchInFiles(arg1:string,arg2:string):Promise<Array<main.SearchResult>>;

export function SetGitConfig(arg1:string,arg2:string):Promise<void>;
