// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddGitRemote(arg1, arg2) {
  return window['go']['main']['App']['AddGitRemote'](arg1, arg2);
}

export function CreateNewFile(arg1) {
  return window['go']['main']['App']['CreateNewFile'](arg1);
}

export function CreateNewFolder(arg1) {
  return window['go']['main']['App']['CreateNewFolder'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function FTPConnect(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['FTPConnect'](arg1, arg2, arg3, arg4);
}

export function FTPDisconnect() {
  return window['go']['main']['App']['FTPDisconnect']();
}

export function FTPReadFile(arg1) {
  return window['go']['main']['App']['FTPReadFile'](arg1);
}

export function FTPSaveFile(arg1, arg2) {
  return window['go']['main']['App']['FTPSaveFile'](arg1, arg2);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetFolderContents(arg1) {
  return window['go']['main']['App']['GetFolderContents'](arg1);
}

export function GetGitStatus(arg1) {
  return window['go']['main']['App']['GetGitStatus'](arg1);
}

export function GitCommitAndPush(arg1, arg2) {
  return window['go']['main']['App']['GitCommitAndPush'](arg1, arg2);
}

export function GitInit(arg1) {
  return window['go']['main']['App']['GitInit'](arg1);
}

export function GitPull(arg1) {
  return window['go']['main']['App']['GitPull'](arg1);
}

export function GitReset(arg1) {
  return window['go']['main']['App']['GitReset'](arg1);
}

export function OpenFile() {
  return window['go']['main']['App']['OpenFile']();
}

export function OpenFolderDialog() {
  return window['go']['main']['App']['OpenFolderDialog']();
}

export function ReadFileByPath(arg1) {
  return window['go']['main']['App']['ReadFileByPath'](arg1);
}

export function RenameItem(arg1, arg2) {
  return window['go']['main']['App']['RenameItem'](arg1, arg2);
}

export function RunCommand(arg1, arg2) {
  return window['go']['main']['App']['RunCommand'](arg1, arg2);
}

export function RunLiveCommand(arg1, arg2) {
  return window['go']['main']['App']['RunLiveCommand'](arg1, arg2);
}

export function SaveFile(arg1, arg2) {
  return window['go']['main']['App']['SaveFile'](arg1, arg2);
}

export function SearchInFiles(arg1, arg2) {
  return window['go']['main']['App']['SearchInFiles'](arg1, arg2);
}

export function SetGitConfig(arg1, arg2) {
  return window['go']['main']['App']['SetGitConfig'](arg1, arg2);
}

export function StopLiveCommand() {
  return window['go']['main']['App']['StopLiveCommand']();
}
